# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
builds:
- env:
  - CGO_ENABLED=0
  - GO111MODULE=on
  main: ./cmd/termshark/termshark.go
  goos:
    - freebsd
    - netbsd
    - openbsd
    - windows
    - linux
    - darwin
  goarch:
    - arm
    - arm64
    - amd64
  ignore:
    - goos: darwin
      goarch: arm
    - goos: freebsd
      goarch: arm
    - goos: netbsd
      goarch: arm
    - goos: openbsd
      goarch: arm
    - goos: windows
      goarch: arm
    - goos: freebsd
      goarch: arm64
    - goos: netbsd
      goarch: arm64
    - goos: openbsd
      goarch: arm64
    - goos: windows
      goarch: arm64
archives:
- replacements:
    darwin: macOS
    linux: linux
    windows: windows
    amd64: x64
  wrap_in_directory: true
  format_overrides:
  - goos: windows
    format: zip
  files:
  - none*    
signs:
  - artifacts: checksum
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Env.TERMSHARK_GIT_DESCRIBE }}"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
