// Code generated by pigeon; DO NOT EDIT.

package streams

import (
	"bytes"
	"errors"
	"fmt"
	"io"
	"io/ioutil"
	"math"
	"os"
	"sort"
	"strconv"
	"strings"
	"sync"
	"unicode"
	"unicode/utf8"
)

var g = &grammar{
	rules: []*rule{
		{
			name: "Input",
			pos:  position{line: 45, col: 1, offset: 1065},
			expr: &actionExpr{
				pos: position{line: 45, col: 10, offset: 1074},
				run: (*parser).callonInput1,
				expr: &seqExpr{
					pos: position{line: 45, col: 10, offset: 1074},
					exprs: []interface{}{
						&ruleRefExpr{
							pos:  position{line: 45, col: 10, offset: 1074},
							name: "_",
						},
						&ruleRefExpr{
							pos:  position{line: 45, col: 12, offset: 1076},
							name: "Separator",
						},
						&labeledExpr{
							pos:   position{line: 45, col: 22, offset: 1086},
							label: "follow",
							expr: &ruleRefExpr{
								pos:  position{line: 45, col: 29, offset: 1093},
								name: "Follow",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 45, col: 36, offset: 1100},
							name: "Separator",
						},
						&ruleRefExpr{
							pos:  position{line: 45, col: 46, offset: 1110},
							name: "EOF",
						},
					},
				},
			},
		},
		{
			name: "Separator",
			pos:  position{line: 49, col: 1, offset: 1141},
			expr: &seqExpr{
				pos: position{line: 49, col: 14, offset: 1154},
				exprs: []interface{}{
					&oneOrMoreExpr{
						pos: position{line: 49, col: 14, offset: 1154},
						expr: &litMatcher{
							pos:        position{line: 49, col: 14, offset: 1154},
							val:        "=",
							ignoreCase: false,
						},
					},
					&ruleRefExpr{
						pos:  position{line: 49, col: 19, offset: 1159},
						name: "__",
					},
				},
			},
		},
		{
			name: "DataLines",
			pos:  position{line: 55, col: 1, offset: 1342},
			expr: &actionExpr{
				pos: position{line: 55, col: 14, offset: 1355},
				run: (*parser).callonDataLines1,
				expr: &labeledExpr{
					pos:   position{line: 55, col: 14, offset: 1355},
					label: "dl",
					expr: &choiceExpr{
						pos: position{line: 55, col: 19, offset: 1360},
						alternatives: []interface{}{
							&ruleRefExpr{
								pos:  position{line: 55, col: 19, offset: 1360},
								name: "DataLineBackComplete",
							},
							&ruleRefExpr{
								pos:  position{line: 55, col: 42, offset: 1383},
								name: "DataLineForwardComplete",
							},
						},
					},
				},
			},
		},
		{
			name: "ThrowUndefLabel",
			pos:  position{line: 68, col: 1, offset: 1618},
			expr: &throwExpr{
				pos:   position{line: 68, col: 19, offset: 1636},
				label: "undeflabel",
			},
		},
		{
			name: "DataLineBackComplete",
			pos:  position{line: 70, col: 1, offset: 1651},
			expr: &actionExpr{
				pos: position{line: 70, col: 25, offset: 1675},
				run: (*parser).callonDataLineBackComplete1,
				expr: &labeledExpr{
					pos:   position{line: 70, col: 25, offset: 1675},
					label: "dl",
					expr: &ruleRefExpr{
						pos:  position{line: 70, col: 28, offset: 1678},
						name: "DataLineBack",
					},
				},
			},
		},
		{
			name: "DataLineForwardComplete",
			pos:  position{line: 81, col: 1, offset: 1872},
			expr: &actionExpr{
				pos: position{line: 81, col: 28, offset: 1899},
				run: (*parser).callonDataLineForwardComplete1,
				expr: &labeledExpr{
					pos:   position{line: 81, col: 28, offset: 1899},
					label: "dl",
					expr: &ruleRefExpr{
						pos:  position{line: 81, col: 31, offset: 1902},
						name: "DataLineForward",
					},
				},
			},
		},
		{
			name: "DataLineBack",
			pos:  position{line: 95, col: 1, offset: 2177},
			expr: &actionExpr{
				pos: position{line: 95, col: 17, offset: 2193},
				run: (*parser).callonDataLineBack1,
				expr: &seqExpr{
					pos: position{line: 95, col: 17, offset: 2193},
					exprs: []interface{}{
						&charClassMatcher{
							pos:        position{line: 95, col: 17, offset: 2193},
							val:        "[\\t]",
							chars:      []rune{'\t'},
							ignoreCase: false,
							inverted:   false,
						},
						&labeledExpr{
							pos:   position{line: 95, col: 22, offset: 2198},
							label: "data",
							expr: &ruleRefExpr{
								pos:  position{line: 95, col: 27, offset: 2203},
								name: "Data",
							},
						},
					},
				},
			},
		},
		{
			name: "DataLineForward",
			pos:  position{line: 102, col: 1, offset: 2309},
			expr: &actionExpr{
				pos: position{line: 102, col: 20, offset: 2328},
				run: (*parser).callonDataLineForward1,
				expr: &labeledExpr{
					pos:   position{line: 102, col: 20, offset: 2328},
					label: "data",
					expr: &ruleRefExpr{
						pos:  position{line: 102, col: 25, offset: 2333},
						name: "Data",
					},
				},
			},
		},
		{
			name: "Data",
			pos:  position{line: 106, col: 1, offset: 2400},
			expr: &actionExpr{
				pos: position{line: 106, col: 9, offset: 2408},
				run: (*parser).callonData1,
				expr: &seqExpr{
					pos: position{line: 106, col: 9, offset: 2408},
					exprs: []interface{}{
						&labeledExpr{
							pos:   position{line: 106, col: 9, offset: 2408},
							label: "ds",
							expr: &oneOrMoreExpr{
								pos: position{line: 106, col: 13, offset: 2412},
								expr: &ruleRefExpr{
									pos:  position{line: 106, col: 13, offset: 2412},
									name: "Datum",
								},
							},
						},
						&zeroOrOneExpr{
							pos: position{line: 106, col: 21, offset: 2420},
							expr: &charClassMatcher{
								pos:        position{line: 106, col: 21, offset: 2420},
								val:        "[\\r]",
								chars:      []rune{'\r'},
								ignoreCase: false,
								inverted:   false,
							},
						},
						&charClassMatcher{
							pos:        position{line: 106, col: 27, offset: 2426},
							val:        "[\\n]",
							chars:      []rune{'\n'},
							ignoreCase: false,
							inverted:   false,
						},
					},
				},
			},
		},
		{
			name: "Datum",
			pos:  position{line: 114, col: 1, offset: 2591},
			expr: &actionExpr{
				pos: position{line: 114, col: 10, offset: 2600},
				run: (*parser).callonDatum1,
				expr: &seqExpr{
					pos: position{line: 114, col: 10, offset: 2600},
					exprs: []interface{}{
						&labeledExpr{
							pos:   position{line: 114, col: 10, offset: 2600},
							label: "b1",
							expr: &charClassMatcher{
								pos:        position{line: 114, col: 13, offset: 2603},
								val:        "[0-9a-fA-F]",
								ranges:     []rune{'0', '9', 'a', 'f', 'A', 'F'},
								ignoreCase: false,
								inverted:   false,
							},
						},
						&labeledExpr{
							pos:   position{line: 114, col: 25, offset: 2615},
							label: "b2",
							expr: &charClassMatcher{
								pos:        position{line: 114, col: 28, offset: 2618},
								val:        "[0-9a-fA-F]",
								ranges:     []rune{'0', '9', 'a', 'f', 'A', 'F'},
								ignoreCase: false,
								inverted:   false,
							},
						},
					},
				},
			},
		},
		{
			name: "DataIndex",
			pos:  position{line: 121, col: 1, offset: 2821},
			expr: &actionExpr{
				pos: position{line: 121, col: 14, offset: 2834},
				run: (*parser).callonDataIndex1,
				expr: &seqExpr{
					pos: position{line: 121, col: 14, offset: 2834},
					exprs: []interface{}{
						&labeledExpr{
							pos:   position{line: 121, col: 14, offset: 2834},
							label: "b0",
							expr: &charClassMatcher{
								pos:        position{line: 121, col: 17, offset: 2837},
								val:        "[0-9a-fA-F]",
								ranges:     []rune{'0', '9', 'a', 'f', 'A', 'F'},
								ignoreCase: false,
								inverted:   false,
							},
						},
						&labeledExpr{
							pos:   position{line: 121, col: 29, offset: 2849},
							label: "b1",
							expr: &charClassMatcher{
								pos:        position{line: 121, col: 32, offset: 2852},
								val:        "[0-9a-fA-F]",
								ranges:     []rune{'0', '9', 'a', 'f', 'A', 'F'},
								ignoreCase: false,
								inverted:   false,
							},
						},
						&labeledExpr{
							pos:   position{line: 121, col: 44, offset: 2864},
							label: "b2",
							expr: &charClassMatcher{
								pos:        position{line: 121, col: 47, offset: 2867},
								val:        "[0-9a-fA-F]",
								ranges:     []rune{'0', '9', 'a', 'f', 'A', 'F'},
								ignoreCase: false,
								inverted:   false,
							},
						},
						&labeledExpr{
							pos:   position{line: 121, col: 59, offset: 2879},
							label: "b3",
							expr: &charClassMatcher{
								pos:        position{line: 121, col: 62, offset: 2882},
								val:        "[0-9a-fA-F]",
								ranges:     []rune{'0', '9', 'a', 'f', 'A', 'F'},
								ignoreCase: false,
								inverted:   false,
							},
						},
						&labeledExpr{
							pos:   position{line: 121, col: 74, offset: 2894},
							label: "b4",
							expr: &charClassMatcher{
								pos:        position{line: 121, col: 77, offset: 2897},
								val:        "[0-9a-fA-F]",
								ranges:     []rune{'0', '9', 'a', 'f', 'A', 'F'},
								ignoreCase: false,
								inverted:   false,
							},
						},
						&labeledExpr{
							pos:   position{line: 121, col: 89, offset: 2909},
							label: "b5",
							expr: &charClassMatcher{
								pos:        position{line: 121, col: 92, offset: 2912},
								val:        "[0-9a-fA-F]",
								ranges:     []rune{'0', '9', 'a', 'f', 'A', 'F'},
								ignoreCase: false,
								inverted:   false,
							},
						},
						&labeledExpr{
							pos:   position{line: 121, col: 104, offset: 2924},
							label: "b6",
							expr: &charClassMatcher{
								pos:        position{line: 121, col: 107, offset: 2927},
								val:        "[0-9a-fA-F]",
								ranges:     []rune{'0', '9', 'a', 'f', 'A', 'F'},
								ignoreCase: false,
								inverted:   false,
							},
						},
						&labeledExpr{
							pos:   position{line: 121, col: 119, offset: 2939},
							label: "b7",
							expr: &charClassMatcher{
								pos:        position{line: 121, col: 122, offset: 2942},
								val:        "[0-9a-fA-F]",
								ranges:     []rune{'0', '9', 'a', 'f', 'A', 'F'},
								ignoreCase: false,
								inverted:   false,
							},
						},
					},
				},
			},
		},
		{
			name: "DataSegment",
			pos:  position{line: 134, col: 1, offset: 3618},
			expr: &actionExpr{
				pos: position{line: 134, col: 16, offset: 3633},
				run: (*parser).callonDataSegment1,
				expr: &labeledExpr{
					pos:   position{line: 134, col: 16, offset: 3633},
					label: "ds",
					expr: &oneOrMoreExpr{
						pos: position{line: 134, col: 19, offset: 3636},
						expr: &ruleRefExpr{
							pos:  position{line: 134, col: 21, offset: 3638},
							name: "Datum",
						},
					},
				},
			},
		},
		{
			name: "Node0Clause",
			pos:  position{line: 143, col: 1, offset: 3821},
			expr: &actionExpr{
				pos: position{line: 143, col: 16, offset: 3836},
				run: (*parser).callonNode0Clause1,
				expr: &seqExpr{
					pos: position{line: 143, col: 16, offset: 3836},
					exprs: []interface{}{
						&litMatcher{
							pos:        position{line: 143, col: 16, offset: 3836},
							val:        "Node 0:",
							ignoreCase: false,
						},
						&ruleRefExpr{
							pos:  position{line: 143, col: 26, offset: 3846},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 143, col: 28, offset: 3848},
							label: "node",
							expr: &ruleRefExpr{
								pos:  position{line: 143, col: 33, offset: 3853},
								name: "NodeExpr",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 143, col: 42, offset: 3862},
							name: "__nl",
						},
					},
				},
			},
		},
		{
			name: "Node1Clause",
			pos:  position{line: 148, col: 1, offset: 3935},
			expr: &actionExpr{
				pos: position{line: 148, col: 16, offset: 3950},
				run: (*parser).callonNode1Clause1,
				expr: &seqExpr{
					pos: position{line: 148, col: 16, offset: 3950},
					exprs: []interface{}{
						&litMatcher{
							pos:        position{line: 148, col: 16, offset: 3950},
							val:        "Node 1:",
							ignoreCase: false,
						},
						&ruleRefExpr{
							pos:  position{line: 148, col: 26, offset: 3960},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 148, col: 28, offset: 3962},
							label: "node",
							expr: &ruleRefExpr{
								pos:  position{line: 148, col: 33, offset: 3967},
								name: "NodeExpr",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 148, col: 42, offset: 3976},
							name: "__nl",
						},
					},
				},
			},
		},
		{
			name: "NodeExpr",
			pos:  position{line: 153, col: 1, offset: 4024},
			expr: &actionExpr{
				pos: position{line: 153, col: 13, offset: 4036},
				run: (*parser).callonNodeExpr1,
				expr: &oneOrMoreExpr{
					pos: position{line: 153, col: 13, offset: 4036},
					expr: &charClassMatcher{
						pos:        position{line: 153, col: 13, offset: 4036},
						val:        "[^\\n]",
						chars:      []rune{'\n'},
						ignoreCase: false,
						inverted:   true,
					},
				},
			},
		},
		{
			name: "FollowClause",
			pos:  position{line: 157, col: 1, offset: 4078},
			expr: &actionExpr{
				pos: position{line: 157, col: 17, offset: 4094},
				run: (*parser).callonFollowClause1,
				expr: &seqExpr{
					pos: position{line: 157, col: 17, offset: 4094},
					exprs: []interface{}{
						&litMatcher{
							pos:        position{line: 157, col: 17, offset: 4094},
							val:        "Follow:",
							ignoreCase: false,
						},
						&ruleRefExpr{
							pos:  position{line: 157, col: 27, offset: 4104},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 157, col: 29, offset: 4106},
							label: "fexpr",
							expr: &ruleRefExpr{
								pos:  position{line: 157, col: 35, offset: 4112},
								name: "FollowExpr",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 157, col: 46, offset: 4123},
							name: "__nl",
						},
					},
				},
			},
		},
		{
			name: "FollowExpr",
			pos:  position{line: 161, col: 1, offset: 4154},
			expr: &actionExpr{
				pos: position{line: 161, col: 15, offset: 4168},
				run: (*parser).callonFollowExpr1,
				expr: &oneOrMoreExpr{
					pos: position{line: 161, col: 15, offset: 4168},
					expr: &charClassMatcher{
						pos:        position{line: 161, col: 15, offset: 4168},
						val:        "[a-zA-Z,]",
						chars:      []rune{','},
						ranges:     []rune{'a', 'z', 'A', 'Z'},
						ignoreCase: false,
						inverted:   false,
					},
				},
			},
		},
		{
			name: "FilterClause",
			pos:  position{line: 165, col: 1, offset: 4214},
			expr: &actionExpr{
				pos: position{line: 165, col: 17, offset: 4230},
				run: (*parser).callonFilterClause1,
				expr: &seqExpr{
					pos: position{line: 165, col: 17, offset: 4230},
					exprs: []interface{}{
						&litMatcher{
							pos:        position{line: 165, col: 17, offset: 4230},
							val:        "Filter:",
							ignoreCase: false,
						},
						&ruleRefExpr{
							pos:  position{line: 165, col: 27, offset: 4240},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 165, col: 29, offset: 4242},
							label: "fexpr",
							expr: &ruleRefExpr{
								pos:  position{line: 165, col: 35, offset: 4248},
								name: "FilterExpr",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 165, col: 46, offset: 4259},
							name: "__nl",
						},
					},
				},
			},
		},
		{
			name: "FilterExpr",
			pos:  position{line: 169, col: 1, offset: 4290},
			expr: &actionExpr{
				pos: position{line: 169, col: 15, offset: 4304},
				run: (*parser).callonFilterExpr1,
				expr: &oneOrMoreExpr{
					pos: position{line: 169, col: 15, offset: 4304},
					expr: &charClassMatcher{
						pos:        position{line: 169, col: 15, offset: 4304},
						val:        "[^\\n]",
						chars:      []rune{'\n'},
						ignoreCase: false,
						inverted:   true,
					},
				},
			},
		},
		{
			name: "Header",
			pos:  position{line: 178, col: 1, offset: 4451},
			expr: &actionExpr{
				pos: position{line: 178, col: 11, offset: 4461},
				run: (*parser).callonHeader1,
				expr: &seqExpr{
					pos: position{line: 178, col: 11, offset: 4461},
					exprs: []interface{}{
						&labeledExpr{
							pos:   position{line: 178, col: 11, offset: 4461},
							label: "fc",
							expr: &ruleRefExpr{
								pos:  position{line: 178, col: 14, offset: 4464},
								name: "FollowClause",
							},
						},
						&labeledExpr{
							pos:   position{line: 178, col: 27, offset: 4477},
							label: "fic",
							expr: &ruleRefExpr{
								pos:  position{line: 178, col: 31, offset: 4481},
								name: "FilterClause",
							},
						},
						&labeledExpr{
							pos:   position{line: 178, col: 44, offset: 4494},
							label: "node0",
							expr: &ruleRefExpr{
								pos:  position{line: 178, col: 50, offset: 4500},
								name: "Node0Clause",
							},
						},
						&labeledExpr{
							pos:   position{line: 178, col: 62, offset: 4512},
							label: "node1",
							expr: &ruleRefExpr{
								pos:  position{line: 178, col: 68, offset: 4518},
								name: "Node1Clause",
							},
						},
					},
				},
			},
		},
		{
			name: "Follow",
			pos:  position{line: 208, col: 1, offset: 5268},
			expr: &actionExpr{
				pos: position{line: 208, col: 11, offset: 5278},
				run: (*parser).callonFollow1,
				expr: &seqExpr{
					pos: position{line: 208, col: 11, offset: 5278},
					exprs: []interface{}{
						&labeledExpr{
							pos:   position{line: 208, col: 11, offset: 5278},
							label: "hdr",
							expr: &ruleRefExpr{
								pos:  position{line: 208, col: 15, offset: 5282},
								name: "Header",
							},
						},
						&labeledExpr{
							pos:   position{line: 208, col: 22, offset: 5289},
							label: "data",
							expr: &zeroOrMoreExpr{
								pos: position{line: 208, col: 27, offset: 5294},
								expr: &ruleRefExpr{
									pos:  position{line: 208, col: 27, offset: 5294},
									name: "DataLines",
								},
							},
						},
					},
				},
			},
		},
		{
			name:        "_",
			displayName: "\"whitespace\"",
			pos:         position{line: 219, col: 1, offset: 5544},
			expr: &zeroOrMoreExpr{
				pos: position{line: 219, col: 19, offset: 5562},
				expr: &charClassMatcher{
					pos:        position{line: 219, col: 19, offset: 5562},
					val:        "[ \\n\\t\\r]",
					chars:      []rune{' ', '\n', '\t', '\r'},
					ignoreCase: false,
					inverted:   false,
				},
			},
		},
		{
			name:        "__",
			displayName: "\"mandatory whitespace\"",
			pos:         position{line: 221, col: 1, offset: 5574},
			expr: &oneOrMoreExpr{
				pos: position{line: 221, col: 30, offset: 5603},
				expr: &charClassMatcher{
					pos:        position{line: 221, col: 30, offset: 5603},
					val:        "[ \\n\\t\\r]",
					chars:      []rune{' ', '\n', '\t', '\r'},
					ignoreCase: false,
					inverted:   false,
				},
			},
		},
		{
			name:        "__nl",
			displayName: "\"whitespace and newline\"",
			pos:         position{line: 223, col: 1, offset: 5615},
			expr: &seqExpr{
				pos: position{line: 223, col: 34, offset: 5648},
				exprs: []interface{}{
					&zeroOrMoreExpr{
						pos: position{line: 223, col: 34, offset: 5648},
						expr: &charClassMatcher{
							pos:        position{line: 223, col: 34, offset: 5648},
							val:        "[ \\t\\r]",
							chars:      []rune{' ', '\t', '\r'},
							ignoreCase: false,
							inverted:   false,
						},
					},
					&charClassMatcher{
						pos:        position{line: 223, col: 43, offset: 5657},
						val:        "[\\n]",
						chars:      []rune{'\n'},
						ignoreCase: false,
						inverted:   false,
					},
				},
			},
		},
		{
			name: "EOF",
			pos:  position{line: 225, col: 1, offset: 5663},
			expr: &notExpr{
				pos: position{line: 225, col: 8, offset: 5670},
				expr: &anyMatcher{
					line: 225, col: 9, offset: 5671,
				},
			},
		},
	},
}

func (c *current) onInput1(follow interface{}) (interface{}, error) {
	return follow, nil
}

func (p *parser) callonInput1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onInput1(stack["follow"])
}

func (c *current) onDataLines1(dl interface{}) (interface{}, error) {

	if cb, ok := c.globalStore["callbacks"]; ok {
		if cb, ok := cb.(IOnStreamChunk); ok {
			cb.OnStreamChunk(dl.(Bytes))
		}
	}

	return dl, nil
}

func (p *parser) callonDataLines1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onDataLines1(stack["dl"])
}

func (c *current) onDataLineBackComplete1(dl interface{}) (interface{}, error) {
	if ctx, ok := c.globalStore["context"]; ok {
		ctx := ctx.(parseContext)
		if ctx.Err() != nil {
			panic(StreamParseError{})
		}
	}

	return dl, nil
}

func (p *parser) callonDataLineBackComplete1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onDataLineBackComplete1(stack["dl"])
}

func (c *current) onDataLineForwardComplete1(dl interface{}) (interface{}, error) {
	if ctx, ok := c.globalStore["context"]; ok {
		ctx := ctx.(parseContext)
		if ctx.Err() != nil {
			panic(StreamParseError{})
		}
	}

	return dl, nil
}

func (p *parser) callonDataLineForwardComplete1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onDataLineForwardComplete1(stack["dl"])
}

func (c *current) onDataLineBack1(data interface{}) (interface{}, error) {
	return Bytes{Dirn: Server, Data: data.([]byte)}, nil
}

func (p *parser) callonDataLineBack1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onDataLineBack1(stack["data"])
}

func (c *current) onDataLineForward1(data interface{}) (interface{}, error) {
	return Bytes{Dirn: Client, Data: data.([]byte)}, nil
}

func (p *parser) callonDataLineForward1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onDataLineForward1(stack["data"])
}

func (c *current) onData1(ds interface{}) (interface{}, error) {
	data := make([]byte, 0, len(ds.([]interface{})))
	for _, l := range ds.([]interface{}) {
		data = append(data, l.(byte))
	}
	return data, nil
}

func (p *parser) callonData1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onData1(stack["ds"])
}

func (c *current) onDatum1(b1, b2 interface{}) (interface{}, error) {
	byte1, _ := strconv.ParseUint(string(b1.([]byte)[0]), 16, 4)
	byte2, _ := strconv.ParseUint(string(b2.([]byte)[0]), 16, 4)
	return byte(byte1<<4 | byte2), nil
}

func (p *parser) callonDatum1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onDatum1(stack["b1"], stack["b2"])
}

func (c *current) onDataIndex1(b0, b1, b2, b3, b4, b5, b6, b7 interface{}) (interface{}, error) {
	byte0, _ := strconv.ParseUint(string(b0.([]byte)[0]), 16, 4)
	byte1, _ := strconv.ParseUint(string(b1.([]byte)[0]), 16, 4)
	byte2, _ := strconv.ParseUint(string(b2.([]byte)[0]), 16, 4)
	byte3, _ := strconv.ParseUint(string(b3.([]byte)[0]), 16, 4)
	byte4, _ := strconv.ParseUint(string(b4.([]byte)[0]), 16, 4)
	byte5, _ := strconv.ParseUint(string(b5.([]byte)[0]), 16, 4)
	byte6, _ := strconv.ParseUint(string(b6.([]byte)[0]), 16, 4)
	byte7, _ := strconv.ParseUint(string(b7.([]byte)[0]), 16, 4)
	return uint32(byte0<<28 | byte1<<24 | byte2<<20 | byte3<<16 | byte4<<12 | byte5<<8 | byte6<<4 | byte7), nil
}

func (p *parser) callonDataIndex1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onDataIndex1(stack["b0"], stack["b1"], stack["b2"], stack["b3"], stack["b4"], stack["b5"], stack["b6"], stack["b7"])
}

func (c *current) onDataSegment1(ds interface{}) (interface{}, error) {
	res := make([]byte, 0)
	for _, d := range ds.([]interface{}) {
		res = append(res, d.(byte))
	}
	return res, nil
}

func (p *parser) callonDataSegment1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onDataSegment1(stack["ds"])
}

func (c *current) onNode0Clause1(node interface{}) (interface{}, error) {
	return node, nil
}

func (p *parser) callonNode0Clause1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onNode0Clause1(stack["node"])
}

func (c *current) onNode1Clause1(node interface{}) (interface{}, error) {
	return node, nil
}

func (p *parser) callonNode1Clause1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onNode1Clause1(stack["node"])
}

func (c *current) onNodeExpr1() (interface{}, error) {
	return string(c.text), nil
}

func (p *parser) callonNodeExpr1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onNodeExpr1()
}

func (c *current) onFollowClause1(fexpr interface{}) (interface{}, error) {
	return fexpr, nil
}

func (p *parser) callonFollowClause1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onFollowClause1(stack["fexpr"])
}

func (c *current) onFollowExpr1() (interface{}, error) {
	return string(c.text), nil
}

func (p *parser) callonFollowExpr1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onFollowExpr1()
}

func (c *current) onFilterClause1(fexpr interface{}) (interface{}, error) {
	return fexpr, nil
}

func (p *parser) callonFilterClause1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onFilterClause1(stack["fexpr"])
}

func (c *current) onFilterExpr1() (interface{}, error) {
	return string(c.text), nil
}

func (p *parser) callonFilterExpr1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onFilterExpr1()
}

func (c *current) onHeader1(fc, fic, node0, node1 interface{}) (interface{}, error) {
	fh := FollowHeader{
		Follow: fc.(string),
		Filter: fic.(string),
		Node0:  node0.(string),
		Node1:  node1.(string),
	}

	if cb, ok := c.globalStore["callbacks"]; ok {
		if cb, ok := cb.(IOnStreamHeader); ok {
			cb.OnStreamHeader(fh)
		}
	}

	return fh, nil
}

func (p *parser) callonHeader1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onHeader1(stack["fc"], stack["fic"], stack["node0"], stack["node1"])
}

func (c *current) onFollow1(hdr, data interface{}) (interface{}, error) {

	bytes := make([]Bytes, 0, len(data.([]interface{})))
	for _, dl := range data.([]interface{}) {
		bytes = append(bytes, dl.(Bytes))
	}
	return &FollowStream{
		FollowHeader: hdr.(FollowHeader),
		Bytes:        bytes,
	}, nil
}

func (p *parser) callonFollow1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onFollow1(stack["hdr"], stack["data"])
}

var (
	// errNoRule is returned when the grammar to parse has no rule.
	errNoRule = errors.New("grammar has no rule")

	// errInvalidEntrypoint is returned when the specified entrypoint rule
	// does not exit.
	errInvalidEntrypoint = errors.New("invalid entrypoint")

	// errInvalidEncoding is returned when the source is not properly
	// utf8-encoded.
	errInvalidEncoding = errors.New("invalid encoding")

	// errMaxExprCnt is used to signal that the maximum number of
	// expressions have been parsed.
	errMaxExprCnt = errors.New("max number of expressions parsed")
)

// Option is a function that can set an option on the parser. It returns
// the previous setting as an Option.
type Option func(*parser) Option

// MaxExpressions creates an Option to stop parsing after the provided
// number of expressions have been parsed, if the value is 0 then the parser will
// parse for as many steps as needed (possibly an infinite number).
//
// The default for maxExprCnt is 0.
func MaxExpressions(maxExprCnt uint64) Option {
	return func(p *parser) Option {
		oldMaxExprCnt := p.maxExprCnt
		p.maxExprCnt = maxExprCnt
		return MaxExpressions(oldMaxExprCnt)
	}
}

// Entrypoint creates an Option to set the rule name to use as entrypoint.
// The rule name must have been specified in the -alternate-entrypoints
// if generating the parser with the -optimize-grammar flag, otherwise
// it may have been optimized out. Passing an empty string sets the
// entrypoint to the first rule in the grammar.
//
// The default is to start parsing at the first rule in the grammar.
func Entrypoint(ruleName string) Option {
	return func(p *parser) Option {
		oldEntrypoint := p.entrypoint
		p.entrypoint = ruleName
		if ruleName == "" {
			p.entrypoint = g.rules[0].name
		}
		return Entrypoint(oldEntrypoint)
	}
}

// Statistics adds a user provided Stats struct to the parser to allow
// the user to process the results after the parsing has finished.
// Also the key for the "no match" counter is set.
//
// Example usage:
//
//     input := "input"
//     stats := Stats{}
//     _, err := Parse("input-file", []byte(input), Statistics(&stats, "no match"))
//     if err != nil {
//         log.Panicln(err)
//     }
//     b, err := json.MarshalIndent(stats.ChoiceAltCnt, "", "  ")
//     if err != nil {
//         log.Panicln(err)
//     }
//     fmt.Println(string(b))
//
func Statistics(stats *Stats, choiceNoMatch string) Option {
	return func(p *parser) Option {
		oldStats := p.Stats
		p.Stats = stats
		oldChoiceNoMatch := p.choiceNoMatch
		p.choiceNoMatch = choiceNoMatch
		if p.Stats.ChoiceAltCnt == nil {
			p.Stats.ChoiceAltCnt = make(map[string]map[string]int)
		}
		return Statistics(oldStats, oldChoiceNoMatch)
	}
}

// Debug creates an Option to set the debug flag to b. When set to true,
// debugging information is printed to stdout while parsing.
//
// The default is false.
func Debug(b bool) Option {
	return func(p *parser) Option {
		old := p.debug
		p.debug = b
		return Debug(old)
	}
}

// Memoize creates an Option to set the memoize flag to b. When set to true,
// the parser will cache all results so each expression is evaluated only
// once. This guarantees linear parsing time even for pathological cases,
// at the expense of more memory and slower times for typical cases.
//
// The default is false.
func Memoize(b bool) Option {
	return func(p *parser) Option {
		old := p.memoize
		p.memoize = b
		return Memoize(old)
	}
}

// AllowInvalidUTF8 creates an Option to allow invalid UTF-8 bytes.
// Every invalid UTF-8 byte is treated as a utf8.RuneError (U+FFFD)
// by character class matchers and is matched by the any matcher.
// The returned matched value, c.text and c.offset are NOT affected.
//
// The default is false.
func AllowInvalidUTF8(b bool) Option {
	return func(p *parser) Option {
		old := p.allowInvalidUTF8
		p.allowInvalidUTF8 = b
		return AllowInvalidUTF8(old)
	}
}

// Recover creates an Option to set the recover flag to b. When set to
// true, this causes the parser to recover from panics and convert it
// to an error. Setting it to false can be useful while debugging to
// access the full stack trace.
//
// The default is true.
func Recover(b bool) Option {
	return func(p *parser) Option {
		old := p.recover
		p.recover = b
		return Recover(old)
	}
}

// GlobalStore creates an Option to set a key to a certain value in
// the globalStore.
func GlobalStore(key string, value interface{}) Option {
	return func(p *parser) Option {
		old := p.cur.globalStore[key]
		p.cur.globalStore[key] = value
		return GlobalStore(key, old)
	}
}

// InitState creates an Option to set a key to a certain value in
// the global "state" store.
func InitState(key string, value interface{}) Option {
	return func(p *parser) Option {
		old := p.cur.state[key]
		p.cur.state[key] = value
		return InitState(key, old)
	}
}

// ParseFile parses the file identified by filename.
func ParseFile(filename string, opts ...Option) (i interface{}, err error) {
	f, err := os.Open(filename)
	if err != nil {
		return nil, err
	}
	defer func() {
		if closeErr := f.Close(); closeErr != nil {
			err = closeErr
		}
	}()
	return ParseReader(filename, f, opts...)
}

// ParseReader parses the data from r using filename as information in the
// error messages.
func ParseReader(filename string, r io.Reader, opts ...Option) (interface{}, error) {
	b, err := ioutil.ReadAll(r)
	if err != nil {
		return nil, err
	}

	return Parse(filename, b, opts...)
}

// Parse parses the data from b using filename as information in the
// error messages.
func Parse(filename string, b []byte, opts ...Option) (interface{}, error) {
	return newParser(filename, b, opts...).parse(g)
}

// position records a position in the text.
type position struct {
	line, col, offset int
}

func (p position) String() string {
	return strconv.Itoa(p.line) + ":" + strconv.Itoa(p.col) + " [" + strconv.Itoa(p.offset) + "]"
}

// savepoint stores all state required to go back to this point in the
// parser.
type savepoint struct {
	position
	rn rune
	w  int
}

type current struct {
	pos  position // start position of the match
	text []byte   // raw text of the match

	// state is a store for arbitrary key,value pairs that the user wants to be
	// tied to the backtracking of the parser.
	// This is always rolled back if a parsing rule fails.
	state storeDict

	// globalStore is a general store for the user to store arbitrary key-value
	// pairs that they need to manage and that they do not want tied to the
	// backtracking of the parser. This is only modified by the user and never
	// rolled back by the parser. It is always up to the user to keep this in a
	// consistent state.
	globalStore storeDict
}

type storeDict map[string]interface{}

// the AST types...

type grammar struct {
	pos   position
	rules []*rule
}

type rule struct {
	pos         position
	name        string
	displayName string
	expr        interface{}
}

type choiceExpr struct {
	pos          position
	alternatives []interface{}
}

type actionExpr struct {
	pos  position
	expr interface{}
	run  func(*parser) (interface{}, error)
}

type recoveryExpr struct {
	pos          position
	expr         interface{}
	recoverExpr  interface{}
	failureLabel []string
}

type seqExpr struct {
	pos   position
	exprs []interface{}
}

type throwExpr struct {
	pos   position
	label string
}

type labeledExpr struct {
	pos   position
	label string
	expr  interface{}
}

type expr struct {
	pos  position
	expr interface{}
}

type andExpr expr
type notExpr expr
type zeroOrOneExpr expr
type zeroOrMoreExpr expr
type oneOrMoreExpr expr

type ruleRefExpr struct {
	pos  position
	name string
}

type stateCodeExpr struct {
	pos position
	run func(*parser) error
}

type andCodeExpr struct {
	pos position
	run func(*parser) (bool, error)
}

type notCodeExpr struct {
	pos position
	run func(*parser) (bool, error)
}

type litMatcher struct {
	pos        position
	val        string
	ignoreCase bool
}

type charClassMatcher struct {
	pos             position
	val             string
	basicLatinChars [128]bool
	chars           []rune
	ranges          []rune
	classes         []*unicode.RangeTable
	ignoreCase      bool
	inverted        bool
}

type anyMatcher position

// errList cumulates the errors found by the parser.
type errList []error

func (e *errList) add(err error) {
	*e = append(*e, err)
}

func (e errList) err() error {
	if len(e) == 0 {
		return nil
	}
	e.dedupe()
	return e
}

func (e *errList) dedupe() {
	var cleaned []error
	set := make(map[string]bool)
	for _, err := range *e {
		if msg := err.Error(); !set[msg] {
			set[msg] = true
			cleaned = append(cleaned, err)
		}
	}
	*e = cleaned
}

func (e errList) Error() string {
	switch len(e) {
	case 0:
		return ""
	case 1:
		return e[0].Error()
	default:
		var buf bytes.Buffer

		for i, err := range e {
			if i > 0 {
				buf.WriteRune('\n')
			}
			buf.WriteString(err.Error())
		}
		return buf.String()
	}
}

// parserError wraps an error with a prefix indicating the rule in which
// the error occurred. The original error is stored in the Inner field.
type parserError struct {
	Inner    error
	pos      position
	prefix   string
	expected []string
}

// Error returns the error message.
func (p *parserError) Error() string {
	return p.prefix + ": " + p.Inner.Error()
}

// newParser creates a parser with the specified input source and options.
func newParser(filename string, b []byte, opts ...Option) *parser {
	stats := Stats{
		ChoiceAltCnt: make(map[string]map[string]int),
	}

	p := &parser{
		filename: filename,
		errs:     new(errList),
		data:     b,
		pt:       savepoint{position: position{line: 1}},
		recover:  true,
		cur: current{
			state:       make(storeDict),
			globalStore: make(storeDict),
		},
		maxFailPos:      position{col: 1, line: 1},
		maxFailExpected: make([]string, 0, 20),
		Stats:           &stats,
		// start rule is rule [0] unless an alternate entrypoint is specified
		entrypoint: g.rules[0].name,
	}
	p.setOptions(opts)

	if p.maxExprCnt == 0 {
		p.maxExprCnt = math.MaxUint64
	}

	return p
}

// setOptions applies the options to the parser.
func (p *parser) setOptions(opts []Option) {
	for _, opt := range opts {
		opt(p)
	}
}

type resultTuple struct {
	v   interface{}
	b   bool
	end savepoint
}

const choiceNoMatch = -1

// Stats stores some statistics, gathered during parsing
type Stats struct {
	// ExprCnt counts the number of expressions processed during parsing
	// This value is compared to the maximum number of expressions allowed
	// (set by the MaxExpressions option).
	ExprCnt uint64

	// ChoiceAltCnt is used to count for each ordered choice expression,
	// which alternative is used how may times.
	// These numbers allow to optimize the order of the ordered choice expression
	// to increase the performance of the parser
	//
	// The outer key of ChoiceAltCnt is composed of the name of the rule as well
	// as the line and the column of the ordered choice.
	// The inner key of ChoiceAltCnt is the number (one-based) of the matching alternative.
	// For each alternative the number of matches are counted. If an ordered choice does not
	// match, a special counter is incremented. The name of this counter is set with
	// the parser option Statistics.
	// For an alternative to be included in ChoiceAltCnt, it has to match at least once.
	ChoiceAltCnt map[string]map[string]int
}

type parser struct {
	filename string
	pt       savepoint
	cur      current

	data []byte
	errs *errList

	depth   int
	recover bool
	debug   bool

	memoize bool
	// memoization table for the packrat algorithm:
	// map[offset in source] map[expression or rule] {value, match}
	memo map[int]map[interface{}]resultTuple

	// rules table, maps the rule identifier to the rule node
	rules map[string]*rule
	// variables stack, map of label to value
	vstack []map[string]interface{}
	// rule stack, allows identification of the current rule in errors
	rstack []*rule

	// parse fail
	maxFailPos            position
	maxFailExpected       []string
	maxFailInvertExpected bool

	// max number of expressions to be parsed
	maxExprCnt uint64
	// entrypoint for the parser
	entrypoint string

	allowInvalidUTF8 bool

	*Stats

	choiceNoMatch string
	// recovery expression stack, keeps track of the currently available recovery expression, these are traversed in reverse
	recoveryStack []map[string]interface{}
}

// push a variable set on the vstack.
func (p *parser) pushV() {
	if cap(p.vstack) == len(p.vstack) {
		// create new empty slot in the stack
		p.vstack = append(p.vstack, nil)
	} else {
		// slice to 1 more
		p.vstack = p.vstack[:len(p.vstack)+1]
	}

	// get the last args set
	m := p.vstack[len(p.vstack)-1]
	if m != nil && len(m) == 0 {
		// empty map, all good
		return
	}

	m = make(map[string]interface{})
	p.vstack[len(p.vstack)-1] = m
}

// pop a variable set from the vstack.
func (p *parser) popV() {
	// if the map is not empty, clear it
	m := p.vstack[len(p.vstack)-1]
	if len(m) > 0 {
		// GC that map
		p.vstack[len(p.vstack)-1] = nil
	}
	p.vstack = p.vstack[:len(p.vstack)-1]
}

// push a recovery expression with its labels to the recoveryStack
func (p *parser) pushRecovery(labels []string, expr interface{}) {
	if cap(p.recoveryStack) == len(p.recoveryStack) {
		// create new empty slot in the stack
		p.recoveryStack = append(p.recoveryStack, nil)
	} else {
		// slice to 1 more
		p.recoveryStack = p.recoveryStack[:len(p.recoveryStack)+1]
	}

	m := make(map[string]interface{}, len(labels))
	for _, fl := range labels {
		m[fl] = expr
	}
	p.recoveryStack[len(p.recoveryStack)-1] = m
}

// pop a recovery expression from the recoveryStack
func (p *parser) popRecovery() {
	// GC that map
	p.recoveryStack[len(p.recoveryStack)-1] = nil

	p.recoveryStack = p.recoveryStack[:len(p.recoveryStack)-1]
}

func (p *parser) print(prefix, s string) string {
	if !p.debug {
		return s
	}

	fmt.Printf("%s %d:%d:%d: %s [%#U]\n",
		prefix, p.pt.line, p.pt.col, p.pt.offset, s, p.pt.rn)
	return s
}

func (p *parser) in(s string) string {
	p.depth++
	return p.print(strings.Repeat(" ", p.depth)+">", s)
}

func (p *parser) out(s string) string {
	p.depth--
	return p.print(strings.Repeat(" ", p.depth)+"<", s)
}

func (p *parser) addErr(err error) {
	p.addErrAt(err, p.pt.position, []string{})
}

func (p *parser) addErrAt(err error, pos position, expected []string) {
	var buf bytes.Buffer
	if p.filename != "" {
		buf.WriteString(p.filename)
	}
	if buf.Len() > 0 {
		buf.WriteString(":")
	}
	buf.WriteString(fmt.Sprintf("%d:%d (%d)", pos.line, pos.col, pos.offset))
	if len(p.rstack) > 0 {
		if buf.Len() > 0 {
			buf.WriteString(": ")
		}
		rule := p.rstack[len(p.rstack)-1]
		if rule.displayName != "" {
			buf.WriteString("rule " + rule.displayName)
		} else {
			buf.WriteString("rule " + rule.name)
		}
	}
	pe := &parserError{Inner: err, pos: pos, prefix: buf.String(), expected: expected}
	p.errs.add(pe)
}

func (p *parser) failAt(fail bool, pos position, want string) {
	// process fail if parsing fails and not inverted or parsing succeeds and invert is set
	if fail == p.maxFailInvertExpected {
		if pos.offset < p.maxFailPos.offset {
			return
		}

		if pos.offset > p.maxFailPos.offset {
			p.maxFailPos = pos
			p.maxFailExpected = p.maxFailExpected[:0]
		}

		if p.maxFailInvertExpected {
			want = "!" + want
		}
		p.maxFailExpected = append(p.maxFailExpected, want)
	}
}

// read advances the parser to the next rune.
func (p *parser) read() {
	p.pt.offset += p.pt.w
	rn, n := utf8.DecodeRune(p.data[p.pt.offset:])
	p.pt.rn = rn
	p.pt.w = n
	p.pt.col++
	if rn == '\n' {
		p.pt.line++
		p.pt.col = 0
	}

	if rn == utf8.RuneError && n == 1 { // see utf8.DecodeRune
		if !p.allowInvalidUTF8 {
			p.addErr(errInvalidEncoding)
		}
	}
}

// restore parser position to the savepoint pt.
func (p *parser) restore(pt savepoint) {
	if p.debug {
		defer p.out(p.in("restore"))
	}
	if pt.offset == p.pt.offset {
		return
	}
	p.pt = pt
}

// Cloner is implemented by any value that has a Clone method, which returns a
// copy of the value. This is mainly used for types which are not passed by
// value (e.g map, slice, chan) or structs that contain such types.
//
// This is used in conjunction with the global state feature to create proper
// copies of the state to allow the parser to properly restore the state in
// the case of backtracking.
type Cloner interface {
	Clone() interface{}
}

var statePool = &sync.Pool{
	New: func() interface{} { return make(storeDict) },
}

func (sd storeDict) Discard() {
	for k := range sd {
		delete(sd, k)
	}
	statePool.Put(sd)
}

// clone and return parser current state.
func (p *parser) cloneState() storeDict {
	if p.debug {
		defer p.out(p.in("cloneState"))
	}

	state := statePool.Get().(storeDict)
	for k, v := range p.cur.state {
		if c, ok := v.(Cloner); ok {
			state[k] = c.Clone()
		} else {
			state[k] = v
		}
	}
	return state
}

// restore parser current state to the state storeDict.
// every restoreState should applied only one time for every cloned state
func (p *parser) restoreState(state storeDict) {
	if p.debug {
		defer p.out(p.in("restoreState"))
	}
	p.cur.state.Discard()
	p.cur.state = state
}

// get the slice of bytes from the savepoint start to the current position.
func (p *parser) sliceFrom(start savepoint) []byte {
	return p.data[start.position.offset:p.pt.position.offset]
}

func (p *parser) getMemoized(node interface{}) (resultTuple, bool) {
	if len(p.memo) == 0 {
		return resultTuple{}, false
	}
	m := p.memo[p.pt.offset]
	if len(m) == 0 {
		return resultTuple{}, false
	}
	res, ok := m[node]
	return res, ok
}

func (p *parser) setMemoized(pt savepoint, node interface{}, tuple resultTuple) {
	if p.memo == nil {
		p.memo = make(map[int]map[interface{}]resultTuple)
	}
	m := p.memo[pt.offset]
	if m == nil {
		m = make(map[interface{}]resultTuple)
		p.memo[pt.offset] = m
	}
	m[node] = tuple
}

func (p *parser) buildRulesTable(g *grammar) {
	p.rules = make(map[string]*rule, len(g.rules))
	for _, r := range g.rules {
		p.rules[r.name] = r
	}
}

func (p *parser) parse(g *grammar) (val interface{}, err error) {
	if len(g.rules) == 0 {
		p.addErr(errNoRule)
		return nil, p.errs.err()
	}

	// TODO : not super critical but this could be generated
	p.buildRulesTable(g)

	if p.recover {
		// panic can be used in action code to stop parsing immediately
		// and return the panic as an error.
		defer func() {
			if e := recover(); e != nil {
				if p.debug {
					defer p.out(p.in("panic handler"))
				}
				val = nil
				switch e := e.(type) {
				case error:
					p.addErr(e)
				default:
					p.addErr(fmt.Errorf("%v", e))
				}
				err = p.errs.err()
			}
		}()
	}

	startRule, ok := p.rules[p.entrypoint]
	if !ok {
		p.addErr(errInvalidEntrypoint)
		return nil, p.errs.err()
	}

	p.read() // advance to first rune
	val, ok = p.parseRule(startRule)
	if !ok {
		if len(*p.errs) == 0 {
			// If parsing fails, but no errors have been recorded, the expected values
			// for the farthest parser position are returned as error.
			maxFailExpectedMap := make(map[string]struct{}, len(p.maxFailExpected))
			for _, v := range p.maxFailExpected {
				maxFailExpectedMap[v] = struct{}{}
			}
			expected := make([]string, 0, len(maxFailExpectedMap))
			eof := false
			if _, ok := maxFailExpectedMap["!."]; ok {
				delete(maxFailExpectedMap, "!.")
				eof = true
			}
			for k := range maxFailExpectedMap {
				expected = append(expected, k)
			}
			sort.Strings(expected)
			if eof {
				expected = append(expected, "EOF")
			}
			p.addErrAt(errors.New("no match found, expected: "+listJoin(expected, ", ", "or")), p.maxFailPos, expected)
		}

		return nil, p.errs.err()
	}
	return val, p.errs.err()
}

func listJoin(list []string, sep string, lastSep string) string {
	switch len(list) {
	case 0:
		return ""
	case 1:
		return list[0]
	default:
		return strings.Join(list[:len(list)-1], sep) + " " + lastSep + " " + list[len(list)-1]
	}
}

func (p *parser) parseRule(rule *rule) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseRule " + rule.name))
	}

	if p.memoize {
		res, ok := p.getMemoized(rule)
		if ok {
			p.restore(res.end)
			return res.v, res.b
		}
	}

	start := p.pt
	p.rstack = append(p.rstack, rule)
	p.pushV()
	val, ok := p.parseExpr(rule.expr)
	p.popV()
	p.rstack = p.rstack[:len(p.rstack)-1]
	if ok && p.debug {
		p.print(strings.Repeat(" ", p.depth)+"MATCH", string(p.sliceFrom(start)))
	}

	if p.memoize {
		p.setMemoized(start, rule, resultTuple{val, ok, p.pt})
	}
	return val, ok
}

func (p *parser) parseExpr(expr interface{}) (interface{}, bool) {
	var pt savepoint

	if p.memoize {
		res, ok := p.getMemoized(expr)
		if ok {
			p.restore(res.end)
			return res.v, res.b
		}
		pt = p.pt
	}

	p.ExprCnt++
	if p.ExprCnt > p.maxExprCnt {
		panic(errMaxExprCnt)
	}

	var val interface{}
	var ok bool
	switch expr := expr.(type) {
	case *actionExpr:
		val, ok = p.parseActionExpr(expr)
	case *andCodeExpr:
		val, ok = p.parseAndCodeExpr(expr)
	case *andExpr:
		val, ok = p.parseAndExpr(expr)
	case *anyMatcher:
		val, ok = p.parseAnyMatcher(expr)
	case *charClassMatcher:
		val, ok = p.parseCharClassMatcher(expr)
	case *choiceExpr:
		val, ok = p.parseChoiceExpr(expr)
	case *labeledExpr:
		val, ok = p.parseLabeledExpr(expr)
	case *litMatcher:
		val, ok = p.parseLitMatcher(expr)
	case *notCodeExpr:
		val, ok = p.parseNotCodeExpr(expr)
	case *notExpr:
		val, ok = p.parseNotExpr(expr)
	case *oneOrMoreExpr:
		val, ok = p.parseOneOrMoreExpr(expr)
	case *recoveryExpr:
		val, ok = p.parseRecoveryExpr(expr)
	case *ruleRefExpr:
		val, ok = p.parseRuleRefExpr(expr)
	case *seqExpr:
		val, ok = p.parseSeqExpr(expr)
	case *stateCodeExpr:
		val, ok = p.parseStateCodeExpr(expr)
	case *throwExpr:
		val, ok = p.parseThrowExpr(expr)
	case *zeroOrMoreExpr:
		val, ok = p.parseZeroOrMoreExpr(expr)
	case *zeroOrOneExpr:
		val, ok = p.parseZeroOrOneExpr(expr)
	default:
		panic(fmt.Sprintf("unknown expression type %T", expr))
	}
	if p.memoize {
		p.setMemoized(pt, expr, resultTuple{val, ok, p.pt})
	}
	return val, ok
}

func (p *parser) parseActionExpr(act *actionExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseActionExpr"))
	}

	start := p.pt
	val, ok := p.parseExpr(act.expr)
	if ok {
		p.cur.pos = start.position
		p.cur.text = p.sliceFrom(start)
		state := p.cloneState()
		actVal, err := act.run(p)
		if err != nil {
			p.addErrAt(err, start.position, []string{})
		}
		p.restoreState(state)

		val = actVal
	}
	if ok && p.debug {
		p.print(strings.Repeat(" ", p.depth)+"MATCH", string(p.sliceFrom(start)))
	}
	return val, ok
}

func (p *parser) parseAndCodeExpr(and *andCodeExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseAndCodeExpr"))
	}

	state := p.cloneState()

	ok, err := and.run(p)
	if err != nil {
		p.addErr(err)
	}
	p.restoreState(state)

	return nil, ok
}

func (p *parser) parseAndExpr(and *andExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseAndExpr"))
	}

	pt := p.pt
	state := p.cloneState()
	p.pushV()
	_, ok := p.parseExpr(and.expr)
	p.popV()
	p.restoreState(state)
	p.restore(pt)

	return nil, ok
}

func (p *parser) parseAnyMatcher(any *anyMatcher) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseAnyMatcher"))
	}

	if p.pt.rn == utf8.RuneError && p.pt.w == 0 {
		// EOF - see utf8.DecodeRune
		p.failAt(false, p.pt.position, ".")
		return nil, false
	}
	start := p.pt
	p.read()
	p.failAt(true, start.position, ".")
	return p.sliceFrom(start), true
}

func (p *parser) parseCharClassMatcher(chr *charClassMatcher) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseCharClassMatcher"))
	}

	cur := p.pt.rn
	start := p.pt

	// can't match EOF
	if cur == utf8.RuneError && p.pt.w == 0 { // see utf8.DecodeRune
		p.failAt(false, start.position, chr.val)
		return nil, false
	}

	if chr.ignoreCase {
		cur = unicode.ToLower(cur)
	}

	// try to match in the list of available chars
	for _, rn := range chr.chars {
		if rn == cur {
			if chr.inverted {
				p.failAt(false, start.position, chr.val)
				return nil, false
			}
			p.read()
			p.failAt(true, start.position, chr.val)
			return p.sliceFrom(start), true
		}
	}

	// try to match in the list of ranges
	for i := 0; i < len(chr.ranges); i += 2 {
		if cur >= chr.ranges[i] && cur <= chr.ranges[i+1] {
			if chr.inverted {
				p.failAt(false, start.position, chr.val)
				return nil, false
			}
			p.read()
			p.failAt(true, start.position, chr.val)
			return p.sliceFrom(start), true
		}
	}

	// try to match in the list of Unicode classes
	for _, cl := range chr.classes {
		if unicode.Is(cl, cur) {
			if chr.inverted {
				p.failAt(false, start.position, chr.val)
				return nil, false
			}
			p.read()
			p.failAt(true, start.position, chr.val)
			return p.sliceFrom(start), true
		}
	}

	if chr.inverted {
		p.read()
		p.failAt(true, start.position, chr.val)
		return p.sliceFrom(start), true
	}
	p.failAt(false, start.position, chr.val)
	return nil, false
}

func (p *parser) incChoiceAltCnt(ch *choiceExpr, altI int) {
	choiceIdent := fmt.Sprintf("%s %d:%d", p.rstack[len(p.rstack)-1].name, ch.pos.line, ch.pos.col)
	m := p.ChoiceAltCnt[choiceIdent]
	if m == nil {
		m = make(map[string]int)
		p.ChoiceAltCnt[choiceIdent] = m
	}
	// We increment altI by 1, so the keys do not start at 0
	alt := strconv.Itoa(altI + 1)
	if altI == choiceNoMatch {
		alt = p.choiceNoMatch
	}
	m[alt]++
}

func (p *parser) parseChoiceExpr(ch *choiceExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseChoiceExpr"))
	}

	for altI, alt := range ch.alternatives {
		// dummy assignment to prevent compile error if optimized
		_ = altI

		state := p.cloneState()

		p.pushV()
		val, ok := p.parseExpr(alt)
		p.popV()
		if ok {
			p.incChoiceAltCnt(ch, altI)
			return val, ok
		}
		p.restoreState(state)
	}
	p.incChoiceAltCnt(ch, choiceNoMatch)
	return nil, false
}

func (p *parser) parseLabeledExpr(lab *labeledExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseLabeledExpr"))
	}

	p.pushV()
	val, ok := p.parseExpr(lab.expr)
	p.popV()
	if ok && lab.label != "" {
		m := p.vstack[len(p.vstack)-1]
		m[lab.label] = val
	}
	return val, ok
}

func (p *parser) parseLitMatcher(lit *litMatcher) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseLitMatcher"))
	}

	ignoreCase := ""
	if lit.ignoreCase {
		ignoreCase = "i"
	}
	val := string(strconv.AppendQuote([]byte{}, lit.val)) + ignoreCase // wrap 'lit.val' with double quotes
	start := p.pt
	for _, want := range lit.val {
		cur := p.pt.rn
		if lit.ignoreCase {
			cur = unicode.ToLower(cur)
		}
		if cur != want {
			p.failAt(false, start.position, val)
			p.restore(start)
			return nil, false
		}
		p.read()
	}
	p.failAt(true, start.position, val)
	return p.sliceFrom(start), true
}

func (p *parser) parseNotCodeExpr(not *notCodeExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseNotCodeExpr"))
	}

	state := p.cloneState()

	ok, err := not.run(p)
	if err != nil {
		p.addErr(err)
	}
	p.restoreState(state)

	return nil, !ok
}

func (p *parser) parseNotExpr(not *notExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseNotExpr"))
	}

	pt := p.pt
	state := p.cloneState()
	p.pushV()
	p.maxFailInvertExpected = !p.maxFailInvertExpected
	_, ok := p.parseExpr(not.expr)
	p.maxFailInvertExpected = !p.maxFailInvertExpected
	p.popV()
	p.restoreState(state)
	p.restore(pt)

	return nil, !ok
}

func (p *parser) parseOneOrMoreExpr(expr *oneOrMoreExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseOneOrMoreExpr"))
	}

	var vals []interface{}

	for {
		p.pushV()
		val, ok := p.parseExpr(expr.expr)
		p.popV()
		if !ok {
			if len(vals) == 0 {
				// did not match once, no match
				return nil, false
			}
			return vals, true
		}
		vals = append(vals, val)
	}
}

func (p *parser) parseRecoveryExpr(recover *recoveryExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseRecoveryExpr (" + strings.Join(recover.failureLabel, ",") + ")"))
	}

	p.pushRecovery(recover.failureLabel, recover.recoverExpr)
	val, ok := p.parseExpr(recover.expr)
	p.popRecovery()

	return val, ok
}

func (p *parser) parseRuleRefExpr(ref *ruleRefExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseRuleRefExpr " + ref.name))
	}

	if ref.name == "" {
		panic(fmt.Sprintf("%s: invalid rule: missing name", ref.pos))
	}

	rule := p.rules[ref.name]
	if rule == nil {
		p.addErr(fmt.Errorf("undefined rule: %s", ref.name))
		return nil, false
	}
	return p.parseRule(rule)
}

func (p *parser) parseSeqExpr(seq *seqExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseSeqExpr"))
	}

	vals := make([]interface{}, 0, len(seq.exprs))

	pt := p.pt
	state := p.cloneState()
	for _, expr := range seq.exprs {
		val, ok := p.parseExpr(expr)
		if !ok {
			p.restoreState(state)
			p.restore(pt)
			return nil, false
		}
		vals = append(vals, val)
	}
	return vals, true
}

func (p *parser) parseStateCodeExpr(state *stateCodeExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseStateCodeExpr"))
	}

	err := state.run(p)
	if err != nil {
		p.addErr(err)
	}
	return nil, true
}

func (p *parser) parseThrowExpr(expr *throwExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseThrowExpr"))
	}

	for i := len(p.recoveryStack) - 1; i >= 0; i-- {
		if recoverExpr, ok := p.recoveryStack[i][expr.label]; ok {
			if val, ok := p.parseExpr(recoverExpr); ok {
				return val, ok
			}
		}
	}

	return nil, false
}

func (p *parser) parseZeroOrMoreExpr(expr *zeroOrMoreExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseZeroOrMoreExpr"))
	}

	var vals []interface{}

	for {
		p.pushV()
		val, ok := p.parseExpr(expr.expr)
		p.popV()
		if !ok {
			return vals, true
		}
		vals = append(vals, val)
	}
}

func (p *parser) parseZeroOrOneExpr(expr *zeroOrOneExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseZeroOrOneExpr"))
	}

	p.pushV()
	val, _ := p.parseExpr(expr.expr)
	p.popV()
	// whether it matched or not, consider it a match
	return val, true
}
